// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ohvtufjehwvwvwinbaxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9odnR1ZmplaHd2d3Z3aW5iYXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIyODc1ODIsImV4cCI6MjA1Nzg2MzU4Mn0.o6UTp8JCZ1412Z8VaoQtL2X7VPYWbsV7XVKc48TNf1o";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);